<pre class="metadata">
Title: Android Payment App Provider
Shortname: android-payment-app-provider
Repository: stephenmcgruer/native-app-payment-handler
Status: DREAM
Editor: Stephen McGruer, w3cid 96463, Google https://www.google.com/, smcgruer@chromium.org
Abstract: This technical report describes how Android apps can be exposed by a user agent as payment apps for the web, via the Native App Payment Handler specification.
Markup Shorthands: markdown yes
</pre>

<pre class="anchors">
spec: manifest-incubations; urlPrefix: https://wicg.github.io/manifest-incubations/
    type: dfn
        text:external application resource; url:dfn-external-application-resource
        text:fingerprints; url:dfn-fingerprints
        text:id; url:dfn-id
        text:minimum version; url:dfn-minimum-version
        text:platform; url:dfn-platform
        text:related applications; url:related_applications-member

spec: native-app-payment-handler; urlPrefix: https://stephenmcgruer.github.io/native-app-payment-handler/spec.html
    type: dfn
        text:native payment app provider model; url: native-payment-app-provider-model
        text:native payment app provider; url: native-payment-app-provider
        text:native payment apps; url: native-payment-apps
        text:native-app payment handler; url: native-app-payment-handler
        text:get the list of native payment apps; url: get-the-list-of-native-payment-apps
        text:claimed payment method identifier; url: claimed-payment-method-identifier
        text:claimed third-party origins; url: claimed-third-party-origins
        text:supported delegations; url: supported-delegations
        text:is a related application; url: is-a-related-application
        text:able to handle a payment request; url:able-to-handle-a-payment-request
        text:invoke the native payment app; url:invoke-the-native-payment-app
        text:inform the user agent that the user has changed their payment method; url:inform-the-user-agent-that-the-user-has-changed-their-payment-method
        text:inform the user agent that the user has changed their shipping option; url:inform-the-user-agent-that-the-user-has-changed-their-shipping-option
        text:inform the user agent that the user has changed their shipping address; url:inform-the-user-agent-that-the-user-has-changed-their-shipping-address
        text:update payment details; url:update-payment-details
        text:notify payment details not updated; url:notify-payment-details-not-updated
        text:indicate success; url:indicate-success
        text:indicate user cancellation; url:indicate-user-cancellation
        text:indicate internal error; url:indicate-internal-error
        text:retrieve the converted result details; url:retrieve-the-converted-result-details
    type: enum
        text:PaymentDelegation; url:enumdef-paymentdelegation
    type: enum-value
        text:"shippingAddress"; for:PaymentDelegation; url:dom-paymentdelegation-shippingaddress
        text:"payerName"; for:PaymentDelegation; url:dom-paymentdelegation-payername
        text:"payerPhone"; for:PaymentDelegation; url:dom-paymentdelegation-payerphone
        text:"payerEmail"; for:PaymentDelegation; url:dom-paymentdelegation-payeremail
</pre>

<!-- Manual fix for 'origin' due to HTML spec ambiguity -->
<pre class="anchors">
spec: html; urlPrefix: https://html.spec.whatwg.org/multipage/browsers.html#
    type: dfn
        text: origin; url: concept-origin
</pre>

<pre class="link-defaults">
spec:infra; type:dfn; for:/; text:set
</pre>

<pre class="biblio">
{
    "native-app-payment-handler": {
        "title": "Native-app Payment Handler",
        "href": "https://stephenmcgruer.github.io/native-app-payment-handler/spec.html"
    }
}
</pre>

<div class="non-normative">

*This technical report is non-normative.*

# Introduction # {#sctn-intro}

The [[native-app-payment-handler]] API defines an abstract functional model,
the [=native payment app provider model=], through which user agents can
interact with [=native payment apps=] in order to treat them as [=native-app
payment handlers=] that are accessible via the [[payment-request]] API.

This document describes one concrete implementation of that model, the
[=Android payment app provider=], which defines how a user agent running on the
Android Operating System can interact with other applications on the same
device that want to act as payment apps.

# Android Payment App Provider # {#sctn-android-payment-app-provider}

The <dfn>Android Payment App Provider</dfn> is a [=native payment app
provider=] that defines how a user agent can access Android [=native payment
apps=]. The necessary functionality is built on top of standard Android OS
concepts for cross-application communication and collaboration:

- <a href="https://developer.android.com/guide/topics/manifest/manifest-intro">AndroidManifest.xml</a>
- <a href="https://developer.android.com/guide/topics/intents/intents-filters">Intents</a>
- <a href="https://developer.android.com/develop/background-work/services">Services</a>

## Payment app AndroidManifest.xml ## {#sctn-payment-app-android-manifest}

In order to be visible to the user agent, the Android payment app defines the
following concepts in their `AndroidManifest.xml` file:

- A **mandatory** `PAY` Android activity, which will receive an intent when
    the user agent [[#sctn-invoking|invokes the app]].

- An **optional** `IS_READY_TO_PAY` Android service, which the user agent will
    bind to and call when [[#sctn-hasenrolled-instrument|determining if the
    app can handle a PaymentRequest]].

- An **optional** `UPDATE_PAYMENT_DETAILS` Android service, which the user
    agent will bind to when [[#sctn-dynamic-updates|communicating dynamic
    updates with the invoked payment app]].

If an Android payment app specifies more than one activity or service that
matches one of the above, the user agent behavior is undefined.

### The `PAY` activity ### {#sctn-pay-activity}

The `PAY` activity will receive an intent from the user agent when the user
agent [[#sctn-invoking|invokes the app]] to handle a PaymentRequest. It must be
<a
href="https://developer.android.com/privacy-and-security/risks/android-exported">exported</a>
and have:

- An intent filter with an `org.chromium.intent.action.PAY` action
- An "`org.chromium.default_payment_method_name`" `<meta-data>` tag.
- Optionally, an "`org.chromium.payment_method_names`" `<meta-data>` tag.
- Optionally, an "`org.chromium.payment_supported_delegations`" `<meta-data>` tag.

The "`org.chromium.default_payment_method_name`" tag must have an
`android:value` attribute containing a valid [=url-based payment method
identifier=]. This will be used for [[#sctn-claiming-method-url]].

The "`org.chromium.payment_method_names`" tag, if present, must have an
`android:resource` attribute pointing at a `<string-array>` resource each of
which must be a valid [=url-based payment method identifier=]. This will be
used for [[#sctn-claiming-origins]].

The "`org.chromium.payment_supported_delegations`" tag, if present, must have an
`android:resource` attribute pointing at a `<string-array>` resource listing
the delegation capabilities supported by the payment app (see
[[#sctn-supported-delegations]]).

<div class="example">
<xmp>
  <activity
       android:name=".PaymentActivity"
       android:exported="true">
    <intent-filter>
      <action android:name="org.chromium.intent.action.PAY" />
    </intent-filter>

    <meta-data
        android:name="org.chromium.default_payment_method_name"
        android:value="https://sampleapp.example/pay" />
    <meta-data
        android:name="org.chromium.payment_method_names"
        android:resource="@array/other_payment_method_names" />
    <meta-data
        android:name="org.chromium.payment_supported_delegations"
        android:resource="@array/supported_delegations" />
  </activity>
</xmp>
</div>

<div class="example">
<xmp>
  <resources>
    <string-array name="other_payment_method_names">
      <item>https://anotherapp.example/payment</item>
    </string-array>
    <string-array name="supported_delegations">
      <item>shippingAddress</item>
      <item>payerName</item>
      <item>payerPhone</item>
      <item>payerEmail</item>
    </string-array>
  </resources>
</xmp>
</div>

ISSUE: The chromium.org namespace used here should be replaced by a w3.org one,
       but Chromium currently ships with chromium.org so it would need to be
       updated and a deprecation process followed, etc.

### The `IS_READY_TO_PAY` service ### {#sctn-is-ready-to-pay-service}

The `IS_READY_TO_PAY` service receives calls from the user agent to
[[#sctn-hasenrolled-instrument|determine if the app can handle a
PaymentRequest]]. If present, it must be <a
href="https://developer.android.com/privacy-and-security/risks/android-exported">exported</a>
and have an intent filter with an `org.chromium.intent.action.IS_READY_TO_PAY`
action.

<div class="example">
<xmp>
  <service
      android:name=".IsReadyToPayService"
      android:exported="true">
    <intent-filter>
      <action android:name="org.chromium.intent.action.IS_READY_TO_PAY" />
    </intent-filter>
  </service>
</xmp>
</div>

### The `UPDATE_PAYMENT_DETAILS` service ### {#sctn-update-payment-details-service}

The `UPDATE_PAYMENT_DETAILS` service receives connections from the user agent
when the payment app is invoked to facilitate two-way communication for
[[#sctn-dynamic-updates|dynamic updates]] (e.g. shipping address or payment
method changes). If present, it must be <a
href="https://developer.android.com/privacy-and-security/risks/android-exported">exported</a>
and have an intent filter with an
`org.chromium.intent.action.UPDATE_PAYMENT_DETAILS` action.

<div class="example">
<xmp>
  <service
      android:name=".PaymentDetailsUpdateService"
      android:exported="true">
    <intent-filter>
      <action android:name="org.chromium.intent.action.UPDATE_PAYMENT_DETAILS" />
    </intent-filter>
  </service>
</xmp>
</div>

## User agent app AndroidManifest.xml ## {#sctn-user-agent-android-manifest}

In order to be able to interact with Android [=native payment apps=], the user
agent application <a
href="https://developer.android.com/training/package-visibility/declaring">declares
its package visibility needs</a> for the relevant intent filters in its own
AndroidManifest.xml file, by defining a `<queries>` block that lists the
following actions:

- `"org.chromium.intent.action.PAY"`
- `"org.chromium.intent.action.IS_READY_TO_PAY"`
- `"org.chromium.intent.action.UPDATE_PAYMENT_DETAILS"`

<div class="example">
<xmp>
  <queries>
    <intent>
      <action android:name="org.chromium.intent.action.PAY"/>
    </intent>
    <intent>
      <action android:name="org.chromium.intent.action.IS_READY_TO_PAY"/>
    </intent>
    <intent>
      <action android:name="org.chromium.intent.action.UPDATE_PAYMENT_DETAILS"/>
    </intent>
  </queries>
</xmp>
</div>

## Returning a list of native payment apps ## {#sctn-list-native-payment-apps}

In order to [=get the list of native payment apps=], the user agent performs
the following steps:

1. Create a new Intent object, |intent|, targeting the
     `org.chromium.intent.action.PAY` action.

1. Query the Android OS for the list of activities that can be performed for
     |intent|, for example via <a href="https://developer.android.com/reference/android/content/pm/PackageManager#queryIntentActivities(android.content.Intent,%20int)">PackageManager.queryIntentActivities</a>.

ISSUE: do we need to spec how to turn the resultant info into a list of
     apps? TBD.

## Claiming a method URL ## {#sctn-claiming-method-url}

The [=claimed payment method identifier=] for an Android application, |app|, is
the `android:value` attribute of the `org.chromium.default_payment_method_name`
`<meta-data>` tag in |app|'s AndroidManifest.xml file.

## Claiming a set of origins ## {#sctn-claiming-origins}

The [=set=] of [=claimed third-party origins=] for an Android application,
|app|, is created from the `org.chromium.payment_method_names` `<meta-data>`
tag in |app|'s AndroidManifest.xml file, as follows:

1. Let |paymentMethodIdentifiers| be the value  of the `org.chromium.payment_method_names`
    `<meta-data>` tag.

1. If |paymentMethodIdentifiers| is not a string array, return an empty [=set=].

1. Let |origins| be an empty [=set=].

1. For each string |identifier| in |paymentMethodIdentifiers|:

    1. If |identifier| is not a valid [=url-based payment method identifier=],
        go to the next iteration of the loop.

    1. Let |origin| be the [=origin=] of |identifier|.

    1. Add |origin| to |origins|.

1. Return |origins|.

ISSUE: We need to document why this is an array of method URLs, rather than
just an array of origins.

## Supported delegations ## {#sctn-supported-delegations}

The [=set=] of [=supported delegations=] for an Android application, |app|, is
created from the `org.chromium.payment_supported_delegations` `<meta-data>` tag
in |app|'s `PAY` activity, as follows:

1. Let |delegations| be an empty [=set=].

1. Let |delegationNames| be the string array resource referenced by the
     `org.chromium.payment_supported_delegations` `<meta-data>` tag in |app|'s
     `PAY` activity.

1. If |delegationNames| is null or empty, return |delegations|.

1. For each string |name| in |delegationNames|:

    1. If |name| is equal to `"shippingAddress"`, add
         {{PaymentDelegation/"shippingAddress"}} to |delegations|.

    1. Else if |name| is equal to `"payerName"`, add
         {{PaymentDelegation/"payerName"}} to |delegations|.

    1. Else if |name| is equal to `"payerPhone"`, add
         {{PaymentDelegation/"payerPhone"}} to |delegations|.

    1. Else if |name| is equal to `"payerEmail"`, add
         {{PaymentDelegation/"payerEmail"}} to |delegations|.

    1. Otherwise, ignore |name|.

1. Return |delegations|.

## Checking if a native payment app is a related application for a web app manifest ## {#sctn-checking-related-application}

In order to check if a given Android application, |app|, [=is a related
application=] for a [=application manifest|web app manifest=], |manifest|, the
user agent performs the following steps:

1. Let |packageName| be the package name of |app|.

1. Let |version| be the version of |app|.

1. Let |fingerprint| be ...

    ISSUE: TODO - need to specify how to convert it to a string

1. For each [=related application=], |relatedApplication|, in the [=related
     applications=] of |manifest|:

    1. If |packageName| is not equal to |relatedApplication|'s [=id=], go to
        the next iteration of this loop.

    1. If |version| is less than |relatedApplication|'s [=minimum version=],
        go to the next iteration of this loop.

        ISSUE: Need to define how the comparison is done.

    1. If |fingerprint| does not match |relatedApplication|'s [=fingerprint=],
        go to the next iteration of this loop.

    1. Return `true`.

1. Return `false`.

## Determining if an Android native payment app can handle a {{PaymentRequest}} ## {#sctn-hasenrolled-instrument}

In order to check if an Android application, |app|, is [=able to handle a
payment request=], |request|, the user agent performs the following steps:

1. If |app| does not have a service listed in its AndroidManifest.xml with an
    intent-filter for `org.chromium.intent.action.IS_READY_TO_PAY` (see
    [[#sctn-is-ready-to-pay-service]]), return `false` / `true` TODO

1. If the user agent is in private browsing mode, return `false` / `true` TODO

    ISSUE: Properly link this

1. Call the IS_READY_TO_PAY service (TODO how), passing the following
     information, and wait on the result.

    1. TODO what information to pass

    ISSUE: Properly document this

1. TODO - convert the result to true/false and return that.

ISSUE: Document the privacy concerns.

## Invoking an Android native payment app ## {#sctn-invoking}

In order to [=invoke the native payment app=], |app|, for a {{PaymentRequest}}
|request|, the user agent performs the following steps:

1. Let |packageName| be the Android package name for |app|.
1. Let |activityName| be the Activity name for |app|.

     ISSUE: TODO - these name to be part of some sort of app concept

1. Let |extras| be the result of [=creating an Android bundle=] for |request|.

1. Create an Intent object, |intent|, whose:

    1. Class name is set to the combination of |packageName| and
         |activityName|, e.g. via <a href="https://developer.android.com/reference/android/content/Intent#setClassName(java.lang.String,%20java.lang.String)">Intent.setClassName</a>.

    1. Action is set to `org.chromium.intent.action.IS_READY_TO_PAY`.

    1. Extras are set to |extras|, e.g. via
         <a href="https://developer.android.com/reference/android/content/Intent#putExtras(android.os.Bundle)">Intent.putExtras</a>.

1. Send |intent| to the Android OS in such a way that the user agent will be
     notified on result, e.g. via <a href="https://developer.android.com/reference/android/app/Activity#startActivityForResult(android.content.Intent,%20int)">Activity.startActivityForResult</a>.

## Communicating with an invoked Android native payment app ## {#sctn-dynamic-updates}

In order to support dynamic transaction updates with an invoked [=native
payment app=], |app|, the user agent performs the following steps:

1. TODO, use the service

## Indicating success of an invoked Android native payment app ## {#sctn-indicate-success}

In order for an invoked Android application, |app|, to [=indicate success=]
back to the user agent, |app| performs the following steps:

1. Call <a href="https://developer.android.com/reference/android/app/Activity#setResult(int)">Activity.setResult</a> with <a href="https://developer.android.com/reference/android/app/Activity#RESULT_OK">Activity.RESULT_OK</a> and with an Intent containing:

    1. A "`methodName`" Intent extra, set to the string name of the method being used.

    1. A "`details`" Intent extra, set to a JSON string containing any
        payment-app specific result information.

1. Terminate the |app|'s activity, e.g. via <a href="https://developer.android.com/reference/android/app/Activity#finish()">Activity.finish()</a>.

To [=retrieve the converted result details=], the user agent performs the
following steps:

1. Obtain the Intent bundle from the result via HOW

1. TODO - conversion steps

## Indicating user cancel from an invoked Android native payment app ## {#sctn-indicate-user-cancel}

In order for an invoked Android application, |app|, to [=indicate user cancellation=]
back to the user agent, |app| performs the following steps:

1. Call <a href="https://developer.android.com/reference/android/app/Activity#setResult(int)">Activity.setResult</a> with <a href="https://developer.android.com/reference/android/app/Activity#RESULT_CANCEL">Activity.RESULT_CANCEL</a>.

1. Terminate the |app|'s activity, e.g. via <a href="https://developer.android.com/reference/android/app/Activity#finish()">Activity.finish()</a>.

## Indicating internal error from an invoked Android native payment app ## {#sctn-indicate-app-error}

In order for an invoked Android application, |app|, to [=indicate internal
error=] back to the user agent, |app| performs the following steps:

1. Let |RESULT_INTERNAL_ERROR| be equal to <a href="https://developer.android.com/reference/android/app/Activity#RESULT_FIRST_USER">Activity.RESULT_FIRST_USER</a>.

1. Call <a href="https://developer.android.com/reference/android/app/Activity#setResult(int)">Activity.setResult</a> with |RESULT_INTERNAL_ERROR|.

1. Terminate the |app|'s activity, e.g. via <a href="https://developer.android.com/reference/android/app/Activity#finish()">Activity.finish()</a>.

## Creating an Android bundle ## {#sctn-creating-bundle}

To <dfn>create an Android bundle</dfn> from a {{PaymentRequest}}, |request|,
perform the following steps:

1. Let |bundle| be a new Bundle object.

1. Insert |request|.{{PaymentRequest/id}} into |bundle| with the key
     "`paymentRequestId`".

1. Insert the {{Document/title}} of |request|'s [=relevant global object=]'s
     [=associated Document=] into |bundle| with the key "`merchantName`".

1. Insert |request|.{{PaymentRequest/[[details]]}}.{{PaymentDetailsInit/total}}.{{PaymentItem/amount}}
     into |bundle| with the key "`total`".

     ISSUE: This needs to be serialized to JSON.

1. ISSUE: TODO - handle modifiers

1. ISSUE: TODO - handle shipping options

1. ISSUE: TODO - handle payment options

1. ISSUE: TODO - handle common extras

1. ISSUE: TODO - handle deprecated fields

</div>
