<pre class="metadata">
Title: Native-app Payment Handler
Shortname: native-app-payment-handler
Repository: stephenmcgruer/native-app-payment-handler
Status: DREAM
Editor: Stephen McGruer, w3cid 96463, Google https://www.google.com/, smcgruer@chromium.org
Abstract: This specification defines capabilities that enable native applications to handle requests for payment originating from the web.
Markup Shorthands: markdown yes
</pre>

<pre class="anchors">
spec: manifest-incubations; urlPrefix: https://wicg.github.io/manifest-incubations/
    type: dfn
        text:external application resource; url:dfn-external-application-resource
        text:fingerprints; url:dfn-fingerprints
        text:id; url:dfn-id
        text:platform; url:dfn-platform
        text:related applications; url:related_applications-member

spec: payment-request; urlPrefix: https://w3c.github.io/payment-request/
    type: attribute; for: PaymentRequest
        text: [[response]]; url: dfn-response
    type: dfn
        text:can make payment algorithm; url:dfn-can-make-payment-algorithm
        text:steps to check if a payment can be made; url:dfn-steps-to-check-if-a-payment-can-be-made
        text:steps to respond to a payment request; url:dfn-steps-to-respond-to-a-payment-request
        text:shipping option changed algorithm; url:dfn-shipping-option-changed-algorithm
        text:shipping address changed algorithm; url:dfn-shipping-address-changed-algorithm
        text:update a PaymentRequest's details algorithm; url:dfn-update-a-paymentrequest-s-details-algorithm
    type: dictionary
        text:AddressInit; url:dom-addressinit
        text:AddressErrors; url:dom-addresserrors

spec: appmanifest; urlPrefix: https://w3c.github.io/manifest/;
    type: dfn
        text: steps for processing a web app manifest; url: #dfn-processing-a-manifest
</pre>

<!-- Manual fix for 'origin' due to HTML spec ambiguity -->
<pre class="anchors">
spec: html; urlPrefix: https://html.spec.whatwg.org/multipage/browsers.html#
    type: dfn
        text: origin; url: concept-origin
</pre>

<pre class="link-defaults">
spec:infra; type:dfn; for:/; text:set
spec:infra; type:dfn; for:/; text:list
spec:url; type:dfn; for:/; text:url
</pre>

<pre class="biblio">
{
    "android-payment-app-provider": {
        "title": "Android Payment App Provider",
        "href": "https://www.stephenmcgruer.com/native-app-payment-handler/android-apps.html"
    }
}
</pre>

<style>
/* The heading colors reference https://www.w3.org/StyleSheets/TR/2021/base.css */
:root {
  --note-heading-text: var(--bg);
  --note-heading-bg: var(--note-text);
}
@media (prefers-color-scheme: dark) {
  :root {
    --note-heading-text: var(--bg);
    --note-heading-bg: var(--note-text);
  }
}

/* The .domintro style is reused from https://resources.whatwg.org/standard.css
   and https://resources.whatwg.org/spec.css */
.domintro {
  margin: 1.5em 0;
  padding: 0.5em 1em;
}
li > .domintro {
  margin: 1em 0;
}
.domintro > :first-child, .domintro > .self-link:first-child + * {
  margin-top: 0;
}
.domintro > :last-child {
  margin-bottom: 0;
}

/* These ones have decorations */
.domintro {
  position: relative;

  /* top gets extra 0.5em (both above and below) for the decoration;
     then we add the padding to the bottom as well for symmetry */
  margin-top: 2em;
  padding-top: 1em;
  padding-bottom: 1em;
}
li > .domintro {
  margin-top: 1.5em;
}
.domintro::before {
  padding: 0.15em 0.25em;
  position: absolute;
  top: -0.8em;
  left: -0.8em;
}

.domintro {
  color: var(--note-text);
  background: var(--note-bg);
}
.domintro::before {
  color:  var(--note-heading-text);
  background: var(--note-heading-bg);
}
.domintro dt, .domintro dt * {
  color: var(--text);
}
.domintro dd p {
  margin: 0.5em 0;
}
.domintro dd p:first-child {
  margin-top: 0;
}
.domintro dd p:last-child {
  margin-bottom: 0;
}
.domintro dd p + p.note, .domintro dd p + p.warning {
  /* Fix the gap above */
  margin-top: 1.3em;
  /* 1.3em = 0.5em + 0.8em */
  /* 0.5em = margin-bottom of .domintro dd p */
  /* 0.8em = top of .note::before */
}
.domintro dd span.note {
  /* Differentiate inline notes from the background */
  border: thin solid;
  border-left: none;
  padding-top: 0.15em; /* 0.15em = padding-top of .note::before */
  padding-bottom: 0.15em;
}

dl.domintro::before { content: 'For web developers (non-normative)'; }
</style>

<div class="non-normative">

# Introduction # {#sctn-intro}

*This section is non-normative.*

This specification defines functionality allowing a native application to
handle payment requests that originate on the web on behalf of users. Such
applications are referred to as [=native-app payment handlers=]. [=Native-app
payment handlers=] are accessed via an abstract "provider", the [=native
payment app provider model=], to avoid specifying details of specific operating
systems or other integrations. The [=native payment app provider model=] has
abstract operations which can be supported by concrete providers.

For examples of concrete providers, see [[#sctn-examples]].

</div>

# Native-app payment handlers # {#sctn-native-app-payment-handler}

A <dfn>native-app payment handler</dfn> is a [=payment handler=], as defined in
[[payment-request]], that is backed by some underlying [=native payment app=]
that can be accessed via a [=native payment app provider=].

This section describes the steps the user agent MUST take when intermediating
between a {{PaymentRequest}} object and one or more [=native payment apps=] from
a single [=native payment app provider=].

## Integration with [[payment-request]] ## {#sctn-integration-with-payment-request}

### Can make payment algorithm ### {#sctn-can-make-payment-algorithm}

When performing step 8.2. of the [=can make payment algorithm=] from
[[payment-request]] for a [=payment method identifier=] |identifier|, which
determines if the user agent has a [=payment handler=] that supports handling
payment requests for |identifier|, the user agent MUST perform the following
steps:

1. For each available [=native payment app provider=] |provider|:

    1. [=Get the list of native payment apps=] known to |provider|. Let the
         result be |paymentApps|.

    1. For each |paymentApp| in |paymentApps|:

         1. If |paymentApp| [=is allowed to handle the payment method
              identifier=] |identifier|, resolve `hasHandlerPromise` with `true`
              and terminate any remaining steps.

### The show() method ### {#sctn-show-method}

When performing step 17.5. of the {{PaymentRequest/show|PaymentRequest.show()}}
method for a {{PaymentRequest}}, which constructs the list of registered
payment handlers for a [=payment method identifier=] |identifier|, the user
agent MUST perform the following steps:

1. For each available [=native payment app provider=] |provider|:

    1. [=Get the list of native payment apps=] known to |provider|. Let the
         result be |paymentApps|.

    1. For each |paymentApp| in |paymentApps|:

         1. If |paymentApp| [=is allowed to handle the payment method
              identifier=] |identifier|, create a [=native-app payment handler=]
              for |paymentApp| and append it to the list of registered payment
              handlers.

When a [=native-app payment handler=] is selected by the user (steps 19-24 of
the show() algorithm), the user agent MUST [=invoke the native payment app=]
corresponding to the selected [=native-app payment handler=], passing the
transaction details and any requested {{PaymentOptions}}.

ISSUE(1): The [[payment-request]] spec is quite vague about what data is or
should be passed to an invoked payment handler. We should be more specific.

NOTE: The invoked payment app will ultimately communicate a result back to the
user agent, either by [=indicating success=], [=indicating user cancellation=],
or [=indicating internal error=].

### Steps to check if a payment can be made ### {#sctn-steps-to-check-if-a-payment-can-be-made}

The [=steps to check if a payment can be made=] for a [=native-app payment
handler=] and JSON-serialized {{PaymentMethodData/data|PaymentMethodData.data}}
object are:

1. Return `true`.

NOTE: No steps are necessary here. We have already verified the payment
handler's claims in [[#sctn-show-method]] and made sure that they match the
identifier. No additional filtering is needed based on the serialized
{{PaymentMethodData/data}}.

### Steps to respond to a payment request ### {#sctn-steps-to-respond-to-a-payment-request}

The [=steps to respond to a payment request=] for a {{PaymentRequest}},
|request|, and a [=native-app payment handler=], |handler|, are:

1. Let |app| be the underlying [=native payment app=] for |handler|.

1. Let |result| be the result of [=retrieving the converted result details=]
     for |app|.

1. If the user agent [=delegates shipping address collection=] to |app|:

    1. Let |address| be the result of running the [=create a ContactAddress from
         user-provided input=] algorithm, treating
         |result|.{{NativePaymentHandlerResponse/shippingAddress}} as the
         user-provided input.

    1. Set |request|.{{PaymentRequest/[[response]]}}.{{PaymentResponse/shippingAddress}}
         to |address|.

    1. Set |request|.{{PaymentRequest/[[response]]}}.{{PaymentResponse/shippingOption}}
         to |result|.{{NativePaymentHandlerResponse/shippingOption}}.

1. If the user agent [=delegates payer name collection=] to |app|:

    1. Set |request|.{{PaymentRequest/[[response]]}}.{{PaymentResponse/payerName}}
         to |result|.{{NativePaymentHandlerResponse/payerName}}.

1. If the user agent [=delegates payer email collection=] to |app|:

    1. Set |request|.{{PaymentRequest/[[response]]}}.{{PaymentResponse/payerEmail}}
         to |result|.{{NativePaymentHandlerResponse/payerEmail}}.

1. If the user agent [=delegates payer phone collection=] to |app|:

    1. Set |request|.{{PaymentRequest/[[response]]}}.{{PaymentResponse/payerPhone}}
         to |result|.{{NativePaymentHandlerResponse/payerPhone}}.

1. Return |result|.{{NativePaymentHandlerResponse/details}}.

ISSUE: [[payment-request]] needs to be updated to allow payment handlers to
populate the full {{PaymentResponse}} (e.g., delegated shipping and payer
data), rather than only the {{PaymentResponse/details}}.

### Payment method changed algorithm ### {#sctn-payment-method-changed-algorithm}

When a [=native payment app=], |app|, informs the user agent that the user has
changed their payment method, given optional method-specific details,
|methodDetails| (which is an [=object=] or `null`), the user agent MUST run the
following steps:

1. Let |request| be the active {{PaymentRequest}} for |app|.

1. Let |methodName| be the [=payment method identifier=] of the [=native-app
     payment handler=] corresponding to |app|.

1. Run the [=payment method changed algorithm=] from [[payment-request]] on
     |request| with |methodName| and |methodDetails|. Let |event| be the
     dispatched {{PaymentMethodChangeEvent}}.

1. [=Propagate payment detail updates=] for |event| and |app|.

### Shipping option changed algorithm ### {#sctn-shipping-option-changed-algorithm}

When a [=native payment app=], |app|, informs the user agent that the user has
changed their shipping option to a {{DOMString}}, |shippingOption| (representing
the {{PaymentShippingOption/id}}), the user agent MUST run the following steps:

1. Let |request| be the active {{PaymentRequest}} for |app|.

1. Run the [=shipping option changed algorithm=] from [[payment-request]] on
     |request|, with |shippingOption| as the user-provided input. Let |event| be
     the dispatched {{PaymentRequestUpdateEvent}}.

1. [=Propagate payment detail updates=] for |event| and |app|.

### Shipping address changed algorithm ### {#sctn-shipping-address-changed-algorithm}

When a [=native payment app=], |app|, informs the user agent that the user has
changed their shipping address to an {{AddressInit}} dictionary,
|shippingAddressDict|, the user agent MUST run the following steps:

1. Let |request| be the active {{PaymentRequest}} for |app|.

1. Let |contactAddress| be the result of running the [=create a ContactAddress
     from user-provided input=] algorithm, treating |shippingAddressDict| as the
     user-provided input.

1. Run the [=shipping address changed algorithm=] from [[payment-request]] on
     |request| with |contactAddress|. Let |event| be the dispatched
     {{PaymentRequestUpdateEvent}}.

1. [=Propagate payment detail updates=] for |event| and |app|.

### Propagating payment detail updates ### {#sctn-propagate-payment-details-update}

When a change event |event| (a {{PaymentRequestUpdateEvent}} or
{{PaymentMethodChangeEvent}}) is dispatched on a {{PaymentRequest}}, |request|,
for an active [=native payment app=], |app|, the user agent MUST run the
following steps to <dfn>propagate payment detail updates</dfn>:

1. If {{PaymentRequestUpdateEvent/updateWith()|updateWith(detailsPromise)}} was
     invoked on |event|:

    1. In parallel:

        1. Wait for |detailsPromise| to settle.

        1. If |detailsPromise| resolves with a {{PaymentDetailsUpdate}} |details|:

            1. Let |update| be the result of running [=convert a
                 PaymentDetailsUpdate to a PaymentRequestDetailsUpdate=] with
                 |details| and |app|.

            1. [=Update payment details=] in |app| with |update|.

        1. If |detailsPromise| rejects:

            1. Run the [=user aborts the payment request algorithm=] from
                 [[payment-request]].

1. Otherwise:

    1. [=Notify payment details not updated=] in |app|.

ISSUE: [[payment-request]] assumes the user agent renders the payment UI
itself, and needs to provide formal extension hooks for payment handlers to
receive the resolved {{PaymentDetailsUpdate}} from
{{PaymentRequestUpdateEvent/updateWith()}}.

## Delegating user information collection ## {#sctn-delegation}

When a merchant creates a {{PaymentRequest}} with {{PaymentOptions}} such as
{{PaymentOptions/requestShipping}} or {{PaymentOptions/requestPayerName}}, the
user agent can either collect this information itself, or delegate the
collection of this information to the selected [=native-app payment handler=].

<pre class="idl">
enum PaymentDelegation {
  "shippingAddress",
  "payerName",
  "payerPhone",
  "payerEmail"
};
</pre>

Given a {{PaymentRequest}}, |request|, and a [=native payment app=], |app|:

1. The user agent <dfn>delegates shipping address collection</dfn> to |app| if
     |request|.{{PaymentRequest/[[options]]}}.{{PaymentOptions/requestShipping}} is
     `true` and |app|'s [=supported delegations=] contains
     {{PaymentDelegation/"shippingAddress"}}.

1. The user agent <dfn>delegates payer name collection</dfn> to |app| if
     |request|.{{PaymentRequest/[[options]]}}.{{PaymentOptions/requestPayerName}} is
     `true` and |app|'s [=supported delegations=] contains
     {{PaymentDelegation/"payerName"}}.

1. The user agent <dfn>delegates payer email collection</dfn> to |app| if
     |request|.{{PaymentRequest/[[options]]}}.{{PaymentOptions/requestPayerEmail}} is
     `true` and |app|'s [=supported delegations=] contains
     {{PaymentDelegation/"payerEmail"}}.

1. The user agent <dfn>delegates payer phone collection</dfn> to |app| if
     |request|.{{PaymentRequest/[[options]]}}.{{PaymentOptions/requestPayerPhone}} is
     `true` and |app|'s [=supported delegations=] contains
     {{PaymentDelegation/"payerPhone"}}.

## The NativePaymentHandlerResponse dictionary ## {#sctn-nativepaymenthandlerresponse}

A [=native payment app=] provides its transaction response to the user agent using
the {{NativePaymentHandlerResponse}} dictionary.

<pre class="idl">
dictionary NativePaymentHandlerResponse {
  DOMString methodName;
  object details;
  DOMString? payerName = null;
  DOMString? payerEmail = null;
  DOMString? payerPhone = null;
  AddressInit shippingAddress;
  DOMString? shippingOption = null;
};
</pre>

<dl class="domintro">

: {{NativePaymentHandlerResponse/methodName}}
:: The [=payment method identifier=] for the payment method used to complete the
     transaction.

: {{NativePaymentHandlerResponse/details}}
:: An object containing payment method specific information supplied by the
     native payment app to complete the transaction.

: {{NativePaymentHandlerResponse/payerName}}
:: The payer's name, if payer name collection was delegated to the native
     payment app.

: {{NativePaymentHandlerResponse/payerEmail}}
:: The payer's email address, if payer email collection was delegated to the
     native payment app.

: {{NativePaymentHandlerResponse/payerPhone}}
:: The payer's phone number, if payer phone collection was delegated to the
     native payment app.

: {{NativePaymentHandlerResponse/shippingAddress}}
:: The shipping address selected by the user, if shipping address collection was
     delegated to the native payment app.

: {{NativePaymentHandlerResponse/shippingOption}}
:: The {{PaymentShippingOption/id}} of the shipping option selected by the user,
     if shipping address collection was delegated to the native payment app.

</dl>

## The PaymentRequestDetailsUpdate dictionary ## {#sctn-paymentrequestdetailsupdate}

When a [=native payment app=] communicates an update to the transaction (such as a
change of payment method, shipping option, or shipping address), the user agent
provides the merchant's updated transaction details back to the native payment
app using the {{PaymentRequestDetailsUpdate}} dictionary.

<pre class="idl">
dictionary PaymentRequestDetailsUpdate {
  PaymentCurrencyAmount total;
  sequence&lt;PaymentDetailsModifier&gt; modifiers;
  DOMString error;
  AddressErrors shippingAddressErrors;
  object paymentMethodErrors;
  sequence&lt;PaymentShippingOption&gt; shippingOptions;
};
</pre>

<dl class="domintro">

: {{PaymentRequestDetailsUpdate/total}}
:: An updated total amount for the payment request.

: {{PaymentRequestDetailsUpdate/modifiers}}
:: A sequence of modifiers for supported payment methods.

: {{PaymentRequestDetailsUpdate/error}}
:: An error message string indicating an issue with the transaction details.

: {{PaymentRequestDetailsUpdate/shippingAddressErrors}}
:: An {{AddressErrors}} dictionary containing validation error messages for the
     shipping address.

: {{PaymentRequestDetailsUpdate/paymentMethodErrors}}
:: An object containing validation error messages for the payment method.

: {{PaymentRequestDetailsUpdate/shippingOptions}}
:: A sequence of updated {{PaymentShippingOption}} objects available for the
    transaction.

</dl>

### Converting a PaymentDetailsUpdate to a PaymentRequestDetailsUpdate ### {#sctn-convert-payment-details-update}

Given a {{PaymentDetailsUpdate}}, |details|, and a [=native payment app=],
|app|, the following steps <dfn>convert a PaymentDetailsUpdate to a
PaymentRequestDetailsUpdate</dfn>:

1. Let |update| be a new {{PaymentRequestDetailsUpdate}} dictionary.

1. If |details|["error"] [=map/exists=], set
     |update|.{{PaymentRequestDetailsUpdate/error}} to |details|["error"].

1. If |details|["total"] [=map/exists=], set
     |update|.{{PaymentRequestDetailsUpdate/total}} to
     |details|["total"].{{PaymentItem/amount}}.

1. If the user agent [=delegates shipping address collection=] to |app|:

    1. If |details|["shippingAddressErrors"] [=map/exists=], set
         |update|.{{PaymentRequestDetailsUpdate/shippingAddressErrors}} to
         |details|["shippingAddressErrors"].

    1. If |details|["shippingOptions"] [=map/exists=], set
         |update|.{{PaymentRequestDetailsUpdate/shippingOptions}} to
         |details|["shippingOptions"].

1. If |details|["paymentMethodErrors"] [=map/exists=], set
     |update|.{{PaymentRequestDetailsUpdate/paymentMethodErrors}} to
     |details|["paymentMethodErrors"].

1. If |details|["modifiers"] [=map/exists=]:

    1. Let |matchingModifiers| be a new empty [=list=].

    1. For each |modifier| in |details|["modifiers"]:

        1. If |app| [=is allowed to handle the payment method identifier=]
             |modifier|.{{PaymentDetailsModifier/supportedMethods}}, append
             |modifier| to |matchingModifiers|.

    1. Set |update|.{{PaymentRequestDetailsUpdate/modifiers}} to
         |matchingModifiers|.

1. Return |update|.

## Verifying native-app payment handler claims ## {#sctn-verifying-app-claims}

[=Native payment apps=] have both a [=claimed payment method identifier=] and a
set of [=claimed third-party origins=].  Verification of these claims relies
upon the payment and application manifests specified in
[[payment-method-manifest]] and [[appmanifest]].

ISSUE(2): Should we allow for alternate methods to verify the claims, to
support cases like payment apps built into the browser?

Given a [=payment method identifier=], |identifier|, and a [=native payment
app=], |app|, the following steps determine if |app| <dfn>is allowed to handle
the payment method identifier</dfn> |identifier|:

1. If |identifier| is not a [=URL-based payment method identifier=], return
     `false`.

1. Let |paymentMethodManifest| be the [=ingest payment method
     manifests|ingested=] and [=parsed payment method manifest|parsed=]
     [=payment method manifest=] for |identifier|. If ingestion or parsing
     fails, return `false`.

1. Let |claimedIdentifier| be the [=claimed payment method identifier=]
    for |app|.

1. If |claimedIdentifier| is equal to |identifier|, then:

    1. For each [=URL=] |webAppManifestURL| in |paymentMethodManifest|'s
         [=default applications=]:

        1. Let |webAppManifestString| be the result of [=fetch the web app
             manifest for a default payment app|fetching the web app manifest=]
             at |webAppManifestURL|. If the fetch fails, continue to the next
             iteration of this loop.

        1. Let |webAppManifest| be the result of running the [=steps for
             processing a web app manifest=] given |webAppManifestString|. If
             processing fails, continue to the next iteration of this loop.

        ISSUE: The payment method manifest spec should really cache and attach
               the relevant web-app manifests to the payment method manifest,
               so we don't have to do this.

        1. If |app| [=is a related application=] for |webAppManifest|, return
             `true`.

    1. Return `false`.

1. Otherwise:

    1. Let |claimedOrigins| be the [=claimed third-party origins=] for |app|.

    1. If none of the |claimedOrigins| [=match the origins allowed for a
        payment method identifier|match the origins allowed for=] |identifier|,
        return `false`.

    1. Let |claimedPaymentMethodManifest| be the [=ingest payment method
        manifests|ingested=] and [=parsed payment method manifest|parsed=]
        [=payment method manifest=] for |claimedIdentifier|. If ingestion or
        parsing fails, return `false`.

    1. For each [=URL=] |webAppManifestURL| in |claimedPaymentMethodManifest|'s
         [=default applications=]:

        1. Let |webAppManifestString| be the result of [=fetch the web app
             manifest for a default payment app|fetching the web app manifest=]
             at |webAppManifestURL|. If the fetch fails, continue to the next
             iteration of this loop.

        1. Let |webAppManifest| be the result of running the [=steps for
             processing a web app manifest=] given |webAppManifestString|. If
             processing fails, continue to the next iteration of this loop.

        ISSUE: The payment method manifest spec should really cache and attach
               the relevant web-app manifests to the payment method manifest,
               so we don't have to do this.

        1. If |app| [=is a related application=] for |webAppManifest|, return
             `true`.

    1. Return `false`.

## Match origins allowed for a payment method identifier ## {#sctn-match-origins}

ISSUE(3): This algorithm should probably exist in [[payment-method-manifest]]
          rather than here.

To determine if a [=set=] of [=origins=], |claimedOrigins|, <dfn>match the
origins allowed for a payment method identifier</dfn>, |identifier|, run the
following steps:

1. Let |paymentMethodManifest| be the [=ingest payment method
     manifests|ingested=] and [=parsed payment method manifest|parsed=]
     [=payment method manifest=] for |identifier|. If ingesting or parsing
     fails, return `false`.

1. For each [=origin=] |claimedOrigin| in |claimedOrigins|:

    1. If |claimedOrigin| is equal to |identifier|'s [=origin=], return `true`.

             ISSUE: Is this right? The |identifier| can cause a redirect, so
             what should we be checking against?

    1. If |paymentMethodManifest|'s [=supported origins=] is the string `'*'`,
        return `true`.

    1. If |paymentMethodManifest|'s [=supported origins=] contains
        |claimedOrigin|, return `true`.

        NOTE: The [=supported origins=] can either be the string "*",
              indicating that any [=origin=] is allowed to handle this
              |identifier|, or an explicit [=set=] of allowed [=origins=].

1. Return `false`.

# Native payment app provider model # {#sctn-native-payment-app-model}

The [=native-app payment handler=] API relies on an abstract functional model
through which the user agent can interact with [=native payment apps=]. This
section describes that model.

The <dfn>native payment app provider model</dfn> is an abstract functional
model which describes the behavior of some <dfn>native payment app
provider</dfn> (e.g., the operating system) that facilitates access to
underlying [=native payment apps=]. <dfn>Native payment apps</dfn> are
deliberately loosely defined, simply as some form of application that is not a
web-based application as defined in [[web-based-payment-handler]]. This allows
for user agent flexibility to provide access to, for example, applications that
use web technologies but which are external to the user agent.

Providers MAY implement and expose this abstract model in any way desired, as
long as the normative requirements of the model are met. See
[[#sctn-examples]].

## Returning a list of [=native payment apps=] ## {#sctn-returning-list}

A [=native payment app provider=] MUST provide a method the user agent can call
to <dfn>get the list of native payment apps</dfn> known to the provider. This
method returns a list of [=native payment apps=].

## Claiming a payment method identifier URL ## {#sctn-claiming-method-url}

Given a [=native payment app=], |app|, a [=native payment app provider=] MUST
provide a method the user agent can call to get the <dfn>claimed payment method
identifier</dfn> for |app|. This method returns a [=url-based payment method
identifier=] that |app| claims it is associated with - that is, a [=payment
method identifier=] whose [=payment method manifest=] includes at least one
[=default application=] pointing to a [=application manifest|web app manifest=]
that has |app| as a [=related application=].

The user agent MUST verify that the claim is valid (see
[[#sctn-verifying-app-claims]]).

## Claiming a set of origins ## {#sctn-claiming-origins}

Given a [=native payment app=], |app|, a [=native payment app provider=] MUST
provide a method the user agent can call to get the <dfn>claimed third-party
origins</dfn>. This is a [=set=] of [=origins=] that the [=native payment app=]
claims that it has the right to act on behalf of.

The user agents MUST verify that the claim is valid for each origin (see
[[#sctn-verifying-app-claims]]).

## Supporting delegations ## {#sctn-supported-delegations}

Given a [=native payment app=], |app|, a [=native payment app provider=] MUST
provide a method the user agent can call to get the <dfn>supported
delegations</dfn> for |app|. This method returns a [=set=] of
{{PaymentDelegation}} values that |app| supports.

## Checking if a [=native payment app=] is a related application for a web app manifest ## {#sctn-related-application}

A [=native payment app provider=] MUST provide a method the user agent can call
to determine if a [=native payment app=] <dfn>is a related application</dfn>
for a [=application manifest|web app manifest=]. The [=native payment app
provider=] MAY utilize the information contained in the [=related
applications=] member of the manifest, such as the [=id=], [=platform=], or
[=fingerprints=] of each specified [=external application resource=].

## Determining if a [=native payment app=] can handle a {{PaymentRequest}} ## {#sctn-hasenrolled-instrument}

A [=native payment app provider=] MUST provide a method the user agent can call
to determine if a [=native payment app=] is <dfn export>able to handle a
payment request</dfn> for a given {{PaymentRequest}} |request|. In order to
support this functionality, the user agent MAY pass information about |request|
to the [=native payment app=], subject to the privacy considerations in
[[#sctn-tracking-risks]].

NOTE: This functionality is used to answer the `hasEnrolledInstrument` method
on {{PaymentRequest}}, which was removed from the [[payment-request]]
specification but is still shipping in multiple browser engines.

## Invoking a [=native payment app=] ## {#sctn-invoking}

A [=native payment app provider=] MUST provide a method the user agent can call
to <dfn>invoke the native payment app</dfn> for a given [=native payment app=],
including converting the input data (see [[#sctn-show-method]]) to a form that
the [=native payment app=] understands.

When run, this method MUST pass control of the current experience over to the
invoked [=native payment app=], until the native payment app [=indicates
success=], [=indicates user cancellation=], or [=indicates internal error=].
Depending on the capabilities of the [=native payment app provider=], the
invoked app MAY be displayed partially over the user agent window (to improve
user context and understanding of the flow).

ISSUE(4): We should speak to the privacy issues in a privacy section.

## Changing the payment method ## {#sctn-change-payment-method}

A [=native payment app provider=] MUST provide a method by which an invoked
[=native payment app=] can inform the user agent that the user has changed
their payment method. When run, the [=native payment app provider=] MUST run the
[[#sctn-payment-method-changed-algorithm|payment method changed algorithm]],
converting native-app specific method details into an [=object=] or `null` value.

## Changing the shipping option ## {#sctn-change-shipping-option}

A [=native payment app provider=] MUST provide a method by which an invoked
[=native payment app=] can inform the user agent that the user has changed
their shipping option. When run, the [=native payment app provider=] MUST run the
[[#sctn-shipping-option-changed-algorithm|shipping option changed algorithm]],
converting native-app specific data into a {{DOMString}} representing the
{{PaymentShippingOption/id}} for the selected shipping option.

## Changing the shipping address ## {#sctn-change-shipping-address}

A [=native payment app provider=] MUST provide a method by which an invoked
[=native payment app=] can inform the user agent that the user has changed
their shipping address. When run, the [=native payment app provider=] MUST run the
[[#sctn-shipping-address-changed-algorithm|shipping address changed algorithm]],
converting native-app specific data into an {{AddressInit}} dictionary.

## Updating payment details in an invoked native payment app ## {#sctn-updating-payment-details}

A [=native payment app provider=] MUST provide a method the user agent can call
to <dfn>update payment details</dfn> in an invoked [=native payment app=], given
a {{PaymentRequestDetailsUpdate}} dictionary, |update|. When called, the
provider MUST transmit the updated details to the invoked app, converting the
dictionary fields into a native format.

## Notifying payment details not updated in an invoked native payment app ## {#sctn-notifying-payment-details-not-updated}

A [=native payment app provider=] MUST provide a method the user agent can call
to <dfn>notify payment details not updated</dfn> in an invoked [=native payment
app=]. When called, the provider MUST inform the invoked app that the merchant
made no changes to the transaction details in response to the change event.

## Indicating success of an invoked [=native payment app=] ## {#sctn-indicating-success}

A [=native payment app provider=] MUST provide a way for an invoked [=native
payment app=] to <dfn>indicate success</dfn> back to the user agent. When this
occurs, the user agent MUST run the [=user accepts the payment request
algorithm=] from [[payment-request]].

A [=native payment app provider=] MUST provide a way for the user agent to
<dfn>retrieve the converted result details</dfn> for an invoked [=native
payment app=] that has [=indicated success=]. This method returns a
{{NativePaymentHandlerResponse}} dictionary containing the transaction result,
converting native-app specific response data into the appropriate dictionary
fields.

## Indicating user cancel from an invoked [=native payment app=] ## {#sctn-indicating-user-cancel}

A [=native payment app provider=] MUST provide a way for an invoked [=native
payment app=] to <dfn>indicate user cancellation</dfn> back to the user agent.
When this occurs, the user agent MUST run the [=user aborts the payment request
algorithm=] from [[payment-request]].

## Indicating internal error from an invoked [=native payment app=] ## {#sctn-indicating-internal-error}

A [=native payment app provider=] MUST provide a way for an invoked [=native
payment app=] to <dfn>indicate internal error</dfn> back to the user agent.
When this occurs, the user agent MUST run the [=payment handler indicates an
internal error algorithm=] from [[payment-request]].

<div class="non-normative">

# Security and privacy considerations # {#sctn-security-and-privacy}

## Tracking risks via readiness checks ## {#sctn-tracking-risks}

Probing whether a native payment app is installed or ready to pay (via
{{PaymentRequest/canMakePayment()}} or `hasEnrolledInstrument()`)
presents potential tracking risks:

- **Fingerprinting**: Websites could query multiple payment methods to silently
    fingerprint the user based on the specific set of installed native payment
    apps.
- **App availability**: In addition to fingerprinting risks, a user's installed
    payment apps can leak sensitive information about the user to a website.
    For example, the existence of a specific payment app could reveal user
    geography, banking relationships, or socio-economic status.
- **Website to app communication**: When determining if an app is [=able to
    handle a payment request=], passing transaction context (such as the top-level
    origin or payment method data) to the app allows installed payment apps to
    silently learn what websites the user visits, without explicit user
    interaction or consent.

To mitigate these risks:

- User agents MUST NOT perform background readiness checks with native payment
    apps when operating in private browsing modes.

    TODO: We should add text for this somewhere in the spec, but since
          hasEnrolledInstrument is gone from {{PaymentRequest}} there isn't
          currently a place to hang it from.

TODO: Add more requirements, and note where implementations (Chromium) don't
meet them today.

## Payment method verification and spoofing prevention ## {#sctn-spoofing}

User agents MUST NOT allow a [=URL-based payment method identifier=] to claim a
native app that it doesn't own, or allow a native app to claim a [=URL-based
payment method identifier=] that it doesn't own. To avoid such spoofing:

- User agents MUST only allow [=native payment app providers=] that verify
    native apps against the information present in the [=application
    manifest=], most importantly the package identifier and cryptographic
    signing certificate fingerprints.
- Native apps claiming support for a [=URL-based payment method identifier=]
    MUST be validated against the [=payment method manifest=] for that
    identifier

## Other privacy considerations ## {#sctn-todo-other}

TODO: Are there any other sub-sections we should add here?

# Example implementations of the [=native payment app provider model=] # {#sctn-examples}

*This section is non-normative.*

The following are known implementations of the [=native payment app provider
model=]. The list may be incomplete and is not any form of registry or official
list.

- [[android-payment-app-provider]]

</div>
